package com.layoutxml.sabs.model;

import java.util.ArrayList;
import java.util.List;

public class AdhellPermissionInfo {
    public final String name;
    public final String label;

    public AdhellPermissionInfo(String name, String label) {
        this.name = name;
        this.label = label;

    }

    public static List<AdhellPermissionInfo> loadPermissions() {

        List<AdhellPermissionInfo> lis = new ArrayList<>();
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_ALL_DOWNLOADS","ACCESS ALL DOWNLOADS"));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_BLUETOOTH_SHARE","ACCESS BLUETOOTH SHARE"));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_CACHE_FILESYSTEM","ACCESS CACHE FILESYSTEM"));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_CHECKIN_PROPERTIES","ACCESS CHECKIN PROPERTIES"));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_COARSE_LOCATION","ACCESS COARSE LOCATION"));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_CONTENT_PROVIDERS_EXTERNALLY","ACCESS CONTENT PROVIDERS EXTERNALLY"));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_DOWNLOAD_MANAGER","ACCESS DOWNLOAD MANAGER"));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_DOWNLOAD_MANAGER_ADVANCED","ACCESS DOWNLOAD MANAGER ADVANCED"));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_DRM_CERTIFICATES","ACCESS DRM CERTIFICATES"));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_EPHEMERAL_APPS","ACCESS EPHEMERAL APPS"));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_FINE_LOCATION","ACCESS FINE LOCATION"));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_FM_RADIO","ACCESS FM RADIO"));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_INPUT_FLINGER","ACCESS INPUT FLINGER"));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_KEYGUARD_SECURE_STORAGE","ACCESS KEYGUARD SECURE STORAGE"));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_LOCATION_EXTRA_COMMANDS","ACCESS LOCATION EXTRA COMMANDS"));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_MOCK_LOCATION","ACCESS MOCK LOCATION"));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_MTP","ACCESS MTP"));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_NETWORK_CONDITIONS","ACCESS NETWORK CONDITIONS"));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_NETWORK_STATE","ACCESS NETWORK STATE"));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_NOTIFICATIONS","ACCESS NOTIFICATIONS"));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_NOTIFICATION_POLICY","ACCESS NOTIFICATION POLICY"));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_PDB_STATE","ACCESS PDB STATE"));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_SURFACE_FLINGER","ACCESS SURFACE FLINGER"));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_VOICE_INTERACTION_SERVICE","ACCESS VOICE INTERACTION SERVICE"));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_VR_MANAGER","ACCESS VR MANAGER"));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_WIFI_STATE","ACCESS WIFI STATE"));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_WIMAX_STATE","ACCESS WIMAX STATE"));
        lis.add(new AdhellPermissionInfo("android.permission.ACCOUNT_MANAGER","ACCOUNT MANAGER"));
        lis.add(new AdhellPermissionInfo("android.permission.ALLOW_ANY_CODEC_FOR_PLAYBACK","ALLOW ANY CODEC FOR PLAYBACK"));
        lis.add(new AdhellPermissionInfo("android.permission.ANSWER_PHONE_CALLS","ANSWER PHONE CALLS"));
        lis.add(new AdhellPermissionInfo("android.permission.ASEC_ACCESS","ASEC ACCESS"));
        lis.add(new AdhellPermissionInfo("android.permission.ASEC_CREATE","ASEC CREATE"));
        lis.add(new AdhellPermissionInfo("android.permission.ASEC_DESTROY","ASEC DESTROY"));
        lis.add(new AdhellPermissionInfo("android.permission.ASEC_MOUNT_UNMOUNT","ASEC MOUNT UNMOUNT"));
        lis.add(new AdhellPermissionInfo("android.permission.ASEC_RENAME","ASEC RENAME"));
        lis.add(new AdhellPermissionInfo("android.permission.AUTHENTICATE_ACCOUNTS","AUTHENTICATE ACCOUNTS"));
        lis.add(new AdhellPermissionInfo("android.permission.BACKUP","BACKUP"));
        lis.add(new AdhellPermissionInfo("android.permission.BATTERY_STATS","BATTERY STATS"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_ACCESSIBILITY_SERVICE","BIND ACCESSIBILITY SERVICE"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_APPWIDGET","BIND APPWIDGET"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_CARRIER_MESSAGING_SERVICE","BIND CARRIER MESSAGING SERVICE"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_CARRIER_SERVICES","BIND CARRIER SERVICES"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_CHOOSER_TARGET_SERVICE","BIND CHOOSER TARGET SERVICE"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_CONDITION_PROVIDER_SERVICE","BIND CONDITION PROVIDER SERVICE"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_CONNECTION_SERVICE","BIND CONNECTION SERVICE"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_DEVICE_ADMIN","BIND DEVICE ADMIN"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_DIRECTORY_SEARCH","BIND DIRECTORY SEARCH"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_DREAM_SERVICE","BIND DREAM SERVICE"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_INCALL_SERVICE","BIND INCALL SERVICE"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_INPUT_METHOD","BIND INPUT METHOD"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_INTENT_FILTER_VERIFIER","BIND INTENT FILTER VERIFIER"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_JOB_SERVICE","BIND JOB SERVICE"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_KEYGUARD_APPWIDGET","BIND KEYGUARD APPWIDGET"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_MIDI_DEVICE_SERVICE","BIND MIDI DEVICE SERVICE"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_NFC_SERVICE","BIND NFC SERVICE"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_NOTIFICATION_LISTENER_SERVICE","BIND NOTIFICATION LISTENER SERVICE"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_NOTIFICATION_RANKER_SERVICE","BIND NOTIFICATION RANKER SERVICE"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_PACKAGE_VERIFIER","BIND PACKAGE VERIFIER"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_PRINT_RECOMMENDATION_SERVICE","BIND PRINT RECOMMENDATION SERVICE"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_PRINT_SERVICE","BIND PRINT SERVICE"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_PRINT_SPOOLER_SERVICE","BIND PRINT SPOOLER SERVICE"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_QUICK_SETTINGS_TILE","BIND QUICK SETTINGS TILE"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_REMOTEVIEWS","BIND REMOTEVIEWS"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_REMOTE_DISPLAY","BIND REMOTE DISPLAY"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_ROUTE_PROVIDER","BIND ROUTE PROVIDER"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_RUNTIME_PERMISSION_PRESENTER_SERVICE","BIND RUNTIME PERMISSION PRESENTER SERVICE"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_SCREENING_SERVICE","BIND SCREENING SERVICE"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_TELECOM_CONNECTION_SERVICE","BIND TELECOM CONNECTION SERVICE"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_TEXT_SERVICE","BIND TEXT SERVICE"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_TRUST_AGENT","BIND TRUST AGENT"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_TV_INPUT","BIND TV INPUT"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_TV_REMOTE_SERVICE","BIND TV REMOTE SERVICE"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_VOICE_INTERACTION","BIND VOICE INTERACTION"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_VPN_SERVICE","BIND VPN SERVICE"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_VR_LISTENER_SERVICE","BIND VR LISTENER SERVICE"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_WALLPAPER","BIND WALLPAPER"));
        lis.add(new AdhellPermissionInfo("android.permission.BLUETOOTH","BLUETOOTH"));
        lis.add(new AdhellPermissionInfo("android.permission.BLUETOOTH_ADMIN","BLUETOOTH ADMIN"));
        lis.add(new AdhellPermissionInfo("android.permission.BLUETOOTH_MAP","BLUETOOTH MAP"));
        lis.add(new AdhellPermissionInfo("android.permission.BLUETOOTH_PRIVILEGED","BLUETOOTH PRIVILEGED"));
        lis.add(new AdhellPermissionInfo("android.permission.BLUETOOTH_STACK","BLUETOOTH STACK"));
        lis.add(new AdhellPermissionInfo("android.permission.BODY_SENSORS","BODY SENSORS"));
        lis.add(new AdhellPermissionInfo("android.permission.BRICK","BRICK"));
        lis.add(new AdhellPermissionInfo("android.permission.BROADCAST_CALLLOG_INFO","BROADCAST CALLLOG INFO"));
        lis.add(new AdhellPermissionInfo("android.permission.BROADCAST_NETWORK_PRIVILEGED","BROADCAST NETWORK PRIVILEGED"));
        lis.add(new AdhellPermissionInfo("android.permission.BROADCAST_PACKAGE_REMOVED","BROADCAST PACKAGE REMOVED"));
        lis.add(new AdhellPermissionInfo("android.permission.BROADCAST_PHONE_ACCOUNT_REGISTRATION","BROADCAST PHONE ACCOUNT REGISTRATION"));
        lis.add(new AdhellPermissionInfo("android.permission.BROADCAST_SMS","BROADCAST SMS"));
        lis.add(new AdhellPermissionInfo("android.permission.BROADCAST_STICKY","BROADCAST STICKY"));
        lis.add(new AdhellPermissionInfo("android.permission.BROADCAST_WAP_PUSH","BROADCAST WAP PUSH"));
        lis.add(new AdhellPermissionInfo("android.permission.CACHE_CONTENT","CACHE CONTENT"));
        lis.add(new AdhellPermissionInfo("android.permission.CALL_PHONE","CALL PHONE"));
        lis.add(new AdhellPermissionInfo("android.permission.CALL_PRIVILEGED","CALL PRIVILEGED"));
        lis.add(new AdhellPermissionInfo("android.permission.CAMERA","CAMERA"));
        lis.add(new AdhellPermissionInfo("android.permission.CAMERA_DISABLE_TRANSMIT_LED","CAMERA DISABLE TRANSMIT LED"));
        lis.add(new AdhellPermissionInfo("android.permission.CAMERA_SEND_SYSTEM_EVENTS","CAMERA SEND SYSTEM EVENTS"));
        lis.add(new AdhellPermissionInfo("android.permission.CAPTURE_AUDIO_HOTWORD","CAPTURE AUDIO HOTWORD"));
        lis.add(new AdhellPermissionInfo("android.permission.CAPTURE_AUDIO_OUTPUT","CAPTURE AUDIO OUTPUT"));
        lis.add(new AdhellPermissionInfo("android.permission.CAPTURE_SECURE_VIDEO_OUTPUT","CAPTURE SECURE VIDEO OUTPUT"));
        lis.add(new AdhellPermissionInfo("android.permission.CAPTURE_TV_INPUT","CAPTURE TV INPUT"));
        lis.add(new AdhellPermissionInfo("android.permission.CAPTURE_VIDEO_OUTPUT","CAPTURE VIDEO OUTPUT"));
        lis.add(new AdhellPermissionInfo("android.permission.CARRIER_FILTER_SMS","CARRIER FILTER SMS"));
        lis.add(new AdhellPermissionInfo("android.permission.CHANGE_APP_IDLE_STATE","CHANGE APP IDLE STATE"));
        lis.add(new AdhellPermissionInfo("android.permission.CHANGE_BACKGROUND_DATA_SETTING","CHANGE BACKGROUND DATA SETTING"));
        lis.add(new AdhellPermissionInfo("android.permission.CHANGE_COMPONENT_ENABLED_STATE","CHANGE COMPONENT ENABLED STATE"));
        lis.add(new AdhellPermissionInfo("android.permission.CHANGE_CONFIGURATION","CHANGE CONFIGURATION"));
        lis.add(new AdhellPermissionInfo("android.permission.CHANGE_DEVICE_IDLE_TEMP_WHITELIST","CHANGE DEVICE IDLE TEMP WHITELIST"));
        lis.add(new AdhellPermissionInfo("android.permission.CHANGE_NETWORK_STATE","CHANGE NETWORK STATE"));
        lis.add(new AdhellPermissionInfo("android.permission.CHANGE_WIFI_MULTICAST_STATE","CHANGE WIFI MULTICAST STATE"));
        lis.add(new AdhellPermissionInfo("android.permission.CHANGE_WIFI_STATE","CHANGE WIFI STATE"));
        lis.add(new AdhellPermissionInfo("android.permission.CHANGE_WIMAX_STATE","CHANGE WIMAX STATE"));
        lis.add(new AdhellPermissionInfo("android.permission.CLEAR_APP_CACHE","CLEAR APP CACHE"));
        lis.add(new AdhellPermissionInfo("android.permission.CLEAR_APP_GRANTED_URI_PERMISSIONS","CLEAR APP GRANTED URI PERMISSIONS"));
        lis.add(new AdhellPermissionInfo("android.permission.CLEAR_APP_USER_DATA","CLEAR APP USER DATA"));
        lis.add(new AdhellPermissionInfo("android.permission.CONFIGURE_DISPLAY_COLOR_TRANSFORM","CONFIGURE DISPLAY COLOR TRANSFORM"));
        lis.add(new AdhellPermissionInfo("android.permission.CONFIGURE_WIFI_DISPLAY","CONFIGURE WIFI DISPLAY"));
        lis.add(new AdhellPermissionInfo("android.permission.CONFIRM_FULL_BACKUP","CONFIRM FULL BACKUP"));
        lis.add(new AdhellPermissionInfo("android.permission.CONNECTIVITY_INTERNAL","CONNECTIVITY INTERNAL"));
        lis.add(new AdhellPermissionInfo("android.permission.CONTROL_INCALL_EXPERIENCE","CONTROL INCALL EXPERIENCE"));
        lis.add(new AdhellPermissionInfo("android.permission.CONTROL_KEYGUARD","CONTROL KEYGUARD"));
        lis.add(new AdhellPermissionInfo("android.permission.CONTROL_LOCATION_UPDATES","CONTROL LOCATION UPDATES"));
        lis.add(new AdhellPermissionInfo("android.permission.CONTROL_VPN","CONTROL VPN"));
        lis.add(new AdhellPermissionInfo("android.permission.CONTROL_WIFI_DISPLAY","CONTROL WIFI DISPLAY"));
        lis.add(new AdhellPermissionInfo("android.permission.COPY_PROTECTED_DATA","COPY PROTECTED DATA"));
        lis.add(new AdhellPermissionInfo("android.permission.CREATE_USERS","CREATE USERS"));
        lis.add(new AdhellPermissionInfo("android.permission.CRYPT_KEEPER","CRYPT KEEPER"));
        lis.add(new AdhellPermissionInfo("android.permission.DELETE_CACHE_FILES","DELETE CACHE FILES"));
        lis.add(new AdhellPermissionInfo("android.permission.DELETE_PACKAGES","DELETE PACKAGES"));
        lis.add(new AdhellPermissionInfo("android.permission.DEVICE_POWER","DEVICE POWER"));
        lis.add(new AdhellPermissionInfo("android.permission.DIAGNOSTIC","DIAGNOSTIC"));
        lis.add(new AdhellPermissionInfo("android.permission.DISABLE_KEYGUARD","DISABLE KEYGUARD"));
        lis.add(new AdhellPermissionInfo("android.permission.DISPATCH_NFC_MESSAGE","DISPATCH NFC MESSAGE"));
        lis.add(new AdhellPermissionInfo("android.permission.DISPATCH_PROVISIONING_MESSAGE","DISPATCH PROVISIONING MESSAGE"));
        lis.add(new AdhellPermissionInfo("android.permission.DOWNLOAD_CACHE_NON_PURGEABLE","DOWNLOAD CACHE NON PURGEABLE"));
        lis.add(new AdhellPermissionInfo("android.permission.DUMP","DUMP"));
        lis.add(new AdhellPermissionInfo("android.permission.DVB_DEVICE","DVB DEVICE"));
        lis.add(new AdhellPermissionInfo("android.permission.EXPAND_STATUS_BAR","EXPAND STATUS BAR"));
        lis.add(new AdhellPermissionInfo("android.permission.FACTORY_TEST","FACTORY TEST"));
        lis.add(new AdhellPermissionInfo("android.permission.FILTER_EVENTS","FILTER EVENTS"));
        lis.add(new AdhellPermissionInfo("android.permission.FLASHLIGHT","FLASHLIGHT"));
        lis.add(new AdhellPermissionInfo("android.permission.FORCE_BACK","FORCE BACK"));
        lis.add(new AdhellPermissionInfo("android.permission.FORCE_STOP_PACKAGES","FORCE STOP PACKAGES"));
        lis.add(new AdhellPermissionInfo("android.permission.FRAME_STATS","FRAME STATS"));
        lis.add(new AdhellPermissionInfo("android.permission.FREEZE_SCREEN","FREEZE SCREEN"));
        lis.add(new AdhellPermissionInfo("android.permission.GET_ACCOUNTS","GET ACCOUNTS"));
        lis.add(new AdhellPermissionInfo("android.permission.GET_ACCOUNTS_PRIVILEGED","GET ACCOUNTS PRIVILEGED"));
        lis.add(new AdhellPermissionInfo("android.permission.GET_APP_GRANTED_URI_PERMISSIONS","GET APP GRANTED URI PERMISSIONS"));
        lis.add(new AdhellPermissionInfo("android.permission.GET_APP_OPS_STATS","GET APP OPS STATS"));
        lis.add(new AdhellPermissionInfo("android.permission.GET_DETAILED_TASKS","GET DETAILED TASKS"));
        lis.add(new AdhellPermissionInfo("android.permission.GET_INTENT_SENDER_INTENT","GET INTENT SENDER INTENT"));
        lis.add(new AdhellPermissionInfo("android.permission.GET_PACKAGE_IMPORTANCE","GET PACKAGE IMPORTANCE"));
        lis.add(new AdhellPermissionInfo("android.permission.GET_PACKAGE_SIZE","GET PACKAGE SIZE"));
        lis.add(new AdhellPermissionInfo("android.permission.GET_PASSWORD","GET PASSWORD"));
        lis.add(new AdhellPermissionInfo("android.permission.GET_PROCESS_STATE_AND_OOM_SCORE","GET PROCESS STATE AND OOM SCORE"));
        lis.add(new AdhellPermissionInfo("android.permission.GET_TASKS","GET TASKS"));
        lis.add(new AdhellPermissionInfo("android.permission.GET_TOP_ACTIVITY_INFO","GET TOP ACTIVITY INFO"));
        lis.add(new AdhellPermissionInfo("android.permission.GLOBAL_SEARCH","GLOBAL SEARCH"));
        lis.add(new AdhellPermissionInfo("android.permission.GLOBAL_SEARCH_CONTROL","GLOBAL SEARCH CONTROL"));
        lis.add(new AdhellPermissionInfo("android.permission.GRANT_RUNTIME_PERMISSIONS","GRANT RUNTIME PERMISSIONS"));
        lis.add(new AdhellPermissionInfo("android.permission.HARDWARE_TEST","HARDWARE TEST"));
        lis.add(new AdhellPermissionInfo("android.permission.HDMI_CEC","HDMI CEC"));
        lis.add(new AdhellPermissionInfo("android.permission.INJECT_EVENTS","INJECT EVENTS"));
        lis.add(new AdhellPermissionInfo("android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS","INSTALL GRANT RUNTIME PERMISSIONS"));
        lis.add(new AdhellPermissionInfo("android.permission.INSTALL_LOCATION_PROVIDER","INSTALL LOCATION PROVIDER"));
        lis.add(new AdhellPermissionInfo("android.permission.INSTALL_PACKAGES","INSTALL PACKAGES"));
        lis.add(new AdhellPermissionInfo("android.permission.INTENT_FILTER_VERIFICATION_AGENT","INTENT FILTER VERIFICATION AGENT"));
        lis.add(new AdhellPermissionInfo("android.permission.INTERACT_ACROSS_USERS","INTERACT ACROSS USERS"));
        lis.add(new AdhellPermissionInfo("android.permission.INTERACT_ACROSS_USERS_FULL","INTERACT ACROSS USERS FULL"));
        lis.add(new AdhellPermissionInfo("android.permission.INTERNAL_SYSTEM_WINDOW","INTERNAL SYSTEM WINDOW"));
        lis.add(new AdhellPermissionInfo("android.permission.INTERNET","INTERNET"));
        lis.add(new AdhellPermissionInfo("android.permission.INVOKE_CARRIER_SETUP","INVOKE CARRIER SETUP"));
        lis.add(new AdhellPermissionInfo("android.permission.KILL_BACKGROUND_PROCESSES","KILL BACKGROUND PROCESSES"));
        lis.add(new AdhellPermissionInfo("android.permission.KILL_UID","KILL UID"));
        lis.add(new AdhellPermissionInfo("android.permission.LAUNCH_TRUST_AGENT_SETTINGS","LAUNCH TRUST AGENT SETTINGS"));
        lis.add(new AdhellPermissionInfo("android.permission.LOCAL_MAC_ADDRESS","LOCAL MAC ADDRESS"));
        lis.add(new AdhellPermissionInfo("android.permission.LOCATION_HARDWARE","LOCATION HARDWARE"));
        lis.add(new AdhellPermissionInfo("android.permission.LOOP_RADIO","LOOP RADIO"));
        lis.add(new AdhellPermissionInfo("android.permission.MANAGE_ACCOUNTS","MANAGE ACCOUNTS"));
        lis.add(new AdhellPermissionInfo("android.permission.MANAGE_ACTIVITY_STACKS","MANAGE ACTIVITY STACKS"));
        lis.add(new AdhellPermissionInfo("android.permission.MANAGE_APP_OPS_RESTRICTIONS","MANAGE APP OPS RESTRICTIONS"));
        lis.add(new AdhellPermissionInfo("android.permission.MANAGE_APP_TOKENS","MANAGE APP TOKENS"));
        lis.add(new AdhellPermissionInfo("android.permission.MANAGE_CA_CERTIFICATES","MANAGE CA CERTIFICATES"));
        lis.add(new AdhellPermissionInfo("android.permission.MANAGE_DEVICE_ADMINS","MANAGE DEVICE ADMINS"));
        lis.add(new AdhellPermissionInfo("android.permission.MANAGE_DOCUMENTS","MANAGE DOCUMENTS"));
        lis.add(new AdhellPermissionInfo("android.permission.MANAGE_FINGERPRINT","MANAGE FINGERPRINT"));
        lis.add(new AdhellPermissionInfo("android.permission.MANAGE_MEDIA_PROJECTION","MANAGE MEDIA PROJECTION"));
        lis.add(new AdhellPermissionInfo("android.permission.MANAGE_NETWORK_POLICY","MANAGE NETWORK POLICY"));
        lis.add(new AdhellPermissionInfo("android.permission.MANAGE_NOTIFICATIONS","MANAGE NOTIFICATIONS"));
        lis.add(new AdhellPermissionInfo("android.permission.MANAGE_PROFILE_AND_DEVICE_OWNERS","MANAGE PROFILE AND DEVICE OWNERS"));
        lis.add(new AdhellPermissionInfo("android.permission.MANAGE_SOUND_TRIGGER","MANAGE SOUND TRIGGER"));
        lis.add(new AdhellPermissionInfo("android.permission.MANAGE_USB","MANAGE USB"));
        lis.add(new AdhellPermissionInfo("android.permission.MANAGE_USERS","MANAGE USERS"));
        lis.add(new AdhellPermissionInfo("android.permission.MANAGE_VOICE_KEYPHRASES","MANAGE VOICE KEYPHRASES"));
        lis.add(new AdhellPermissionInfo("android.permission.MASTER_CLEAR","MASTER CLEAR"));
        lis.add(new AdhellPermissionInfo("android.permission.MEDIA_CONTENT_CONTROL","MEDIA CONTENT CONTROL"));
        lis.add(new AdhellPermissionInfo("android.permission.MODIFY_APPWIDGET_BIND_PERMISSIONS","MODIFY APPWIDGET BIND PERMISSIONS"));
        lis.add(new AdhellPermissionInfo("android.permission.MODIFY_AUDIO_ROUTING","MODIFY AUDIO ROUTING"));
        lis.add(new AdhellPermissionInfo("android.permission.MODIFY_AUDIO_SETTINGS","MODIFY AUDIO SETTINGS"));
        lis.add(new AdhellPermissionInfo("android.permission.MODIFY_CELL_BROADCASTS","MODIFY CELL BROADCASTS"));
        lis.add(new AdhellPermissionInfo("android.permission.MODIFY_DAY_NIGHT_MODE","MODIFY DAY NIGHT MODE"));
        lis.add(new AdhellPermissionInfo("android.permission.MODIFY_NETWORK_ACCOUNTING","MODIFY NETWORK ACCOUNTING"));
        lis.add(new AdhellPermissionInfo("android.permission.MODIFY_PARENTAL_CONTROLS","MODIFY PARENTAL CONTROLS"));
        lis.add(new AdhellPermissionInfo("android.permission.MODIFY_PHONE_STATE","MODIFY PHONE STATE"));
        lis.add(new AdhellPermissionInfo("android.permission.MOUNT_FORMAT_FILESYSTEMS","MOUNT FORMAT FILESYSTEMS"));
        lis.add(new AdhellPermissionInfo("android.permission.MOUNT_UNMOUNT_FILESYSTEMS","MOUNT UNMOUNT FILESYSTEMS"));
        lis.add(new AdhellPermissionInfo("android.permission.MOVE_PACKAGE","MOVE PACKAGE"));
        lis.add(new AdhellPermissionInfo("android.permission.NET_ADMIN","NET ADMIN"));
        lis.add(new AdhellPermissionInfo("android.permission.NET_TUNNELING","NET TUNNELING"));
        lis.add(new AdhellPermissionInfo("android.permission.NFC","NFC"));
        lis.add(new AdhellPermissionInfo("android.permission.NFC_HANDOVER_STATUS","NFC HANDOVER STATUS"));
        lis.add(new AdhellPermissionInfo("android.permission.NOTIFY_PENDING_SYSTEM_UPDATE","NOTIFY PENDING SYSTEM UPDATE"));
        lis.add(new AdhellPermissionInfo("android.permission.OBSERVE_GRANT_REVOKE_PERMISSIONS","OBSERVE GRANT REVOKE PERMISSIONS"));
        lis.add(new AdhellPermissionInfo("android.permission.OEM_UNLOCK_STATE","OEM UNLOCK STATE"));
        lis.add(new AdhellPermissionInfo("android.permission.OVERRIDE_WIFI_CONFIG","OVERRIDE WIFI CONFIG"));
        lis.add(new AdhellPermissionInfo("android.permission.PACKAGE_USAGE_STATS","PACKAGE USAGE STATS"));
        lis.add(new AdhellPermissionInfo("android.permission.PACKAGE_VERIFICATION_AGENT","PACKAGE VERIFICATION AGENT"));
        lis.add(new AdhellPermissionInfo("android.permission.PACKET_KEEPALIVE_OFFLOAD","PACKET KEEPALIVE OFFLOAD"));
        lis.add(new AdhellPermissionInfo("android.permission.PEERS_MAC_ADDRESS","PEERS MAC ADDRESS"));
        lis.add(new AdhellPermissionInfo("android.permission.PERFORM_CDMA_PROVISIONING","PERFORM CDMA PROVISIONING"));
        lis.add(new AdhellPermissionInfo("android.permission.PERFORM_SIM_ACTIVATION","PERFORM SIM ACTIVATION"));
        lis.add(new AdhellPermissionInfo("android.permission.PERSISTENT_ACTIVITY","PERSISTENT ACTIVITY"));
        lis.add(new AdhellPermissionInfo("android.permission.PROCESS_CALLLOG_INFO","PROCESS CALLLOG INFO"));
        lis.add(new AdhellPermissionInfo("android.permission.PROCESS_OUTGOING_CALLS","PROCESS OUTGOING CALLS"));
        lis.add(new AdhellPermissionInfo("android.permission.PROCESS_PHONE_ACCOUNT_REGISTRATION","PROCESS PHONE ACCOUNT REGISTRATION"));
        lis.add(new AdhellPermissionInfo("android.permission.PROVIDE_TRUST_AGENT","PROVIDE TRUST AGENT"));
        lis.add(new AdhellPermissionInfo("android.permission.QUERY_DO_NOT_ASK_CREDENTIALS_ON_BOOT","QUERY DO NOT ASK CREDENTIALS ON BOOT"));
        lis.add(new AdhellPermissionInfo("android.permission.READ_BLOCKED_NUMBERS","READ BLOCKED NUMBERS"));
        lis.add(new AdhellPermissionInfo("android.permission.READ_CALENDAR","READ CALENDAR"));
        lis.add(new AdhellPermissionInfo("android.permission.READ_CALL_LOG","READ CALL LOG"));
        lis.add(new AdhellPermissionInfo("android.permission.READ_CLIPBOARD","READ CLIPBOARD"));
        lis.add(new AdhellPermissionInfo("android.permission.READ_CONTACTS","READ CONTACTS"));
        lis.add(new AdhellPermissionInfo("android.permission.READ_DREAM_STATE","READ DREAM STATE"));
        lis.add(new AdhellPermissionInfo("android.permission.READ_EXTERNAL_STORAGE","READ EXTERNAL STORAGE"));
        lis.add(new AdhellPermissionInfo("android.permission.READ_FRAME_BUFFER","READ FRAME BUFFER"));
        lis.add(new AdhellPermissionInfo("android.permission.READ_INPUT_STATE","READ INPUT STATE"));
        lis.add(new AdhellPermissionInfo("android.permission.READ_INSTALL_SESSIONS","READ INSTALL SESSIONS"));
        lis.add(new AdhellPermissionInfo("android.permission.READ_LOGS","READ LOGS"));
        lis.add(new AdhellPermissionInfo("android.permission.READ_NETWORK_USAGE_HISTORY","READ NETWORK USAGE HISTORY"));
        lis.add(new AdhellPermissionInfo("android.permission.READ_OEM_UNLOCK_STATE","READ OEM UNLOCK STATE"));
        lis.add(new AdhellPermissionInfo("android.permission.READ_PHONE_STATE","READ PHONE STATE"));
        lis.add(new AdhellPermissionInfo("android.permission.READ_PRECISE_PHONE_STATE","READ PRECISE PHONE STATE"));
        lis.add(new AdhellPermissionInfo("android.permission.READ_PRIVILEGED_PHONE_STATE","READ PRIVILEGED PHONE STATE"));
        lis.add(new AdhellPermissionInfo("android.permission.READ_PROFILE","READ PROFILE"));
        lis.add(new AdhellPermissionInfo("android.permission.READ_SEARCH_INDEXABLES","READ SEARCH INDEXABLES"));
        lis.add(new AdhellPermissionInfo("android.permission.READ_SMS","READ SMS"));
        lis.add(new AdhellPermissionInfo("android.permission.READ_SOCIAL_STREAM","READ SOCIAL STREAM"));
        lis.add(new AdhellPermissionInfo("android.permission.READ_SYNC_SETTINGS","READ SYNC SETTINGS"));
        lis.add(new AdhellPermissionInfo("android.permission.READ_SYNC_STATS","READ SYNC STATS"));
        lis.add(new AdhellPermissionInfo("android.permission.READ_USER_DICTIONARY","READ USER DICTIONARY"));
        lis.add(new AdhellPermissionInfo("android.permission.READ_WIFI_CREDENTIAL","READ WIFI CREDENTIAL"));
        lis.add(new AdhellPermissionInfo("android.permission.REAL_GET_TASKS","REAL GET TASKS"));
        lis.add(new AdhellPermissionInfo("android.permission.REBOOT","REBOOT"));
        lis.add(new AdhellPermissionInfo("android.permission.RECEIVE_BLUETOOTH_MAP","RECEIVE BLUETOOTH MAP"));
        lis.add(new AdhellPermissionInfo("android.permission.RECEIVE_BOOT_COMPLETED","RECEIVE BOOT COMPLETED"));
        lis.add(new AdhellPermissionInfo("android.permission.RECEIVE_DATA_ACTIVITY_CHANGE","RECEIVE DATA ACTIVITY CHANGE"));
        lis.add(new AdhellPermissionInfo("android.permission.RECEIVE_EMERGENCY_BROADCAST","RECEIVE EMERGENCY BROADCAST"));
        lis.add(new AdhellPermissionInfo("android.permission.RECEIVE_MEDIA_RESOURCE_USAGE","RECEIVE MEDIA RESOURCE USAGE"));
        lis.add(new AdhellPermissionInfo("android.permission.RECEIVE_MMS","RECEIVE MMS"));
        lis.add(new AdhellPermissionInfo("android.permission.RECEIVE_SMS","RECEIVE SMS"));
        lis.add(new AdhellPermissionInfo("android.permission.RECEIVE_STK_COMMANDS","RECEIVE STK COMMANDS"));
        lis.add(new AdhellPermissionInfo("android.permission.RECEIVE_WIFI_CREDENTIAL_CHANGE","RECEIVE WIFI CREDENTIAL CHANGE"));
        lis.add(new AdhellPermissionInfo("android.permission.RECORD_AUDIO","RECORD AUDIO"));
        lis.add(new AdhellPermissionInfo("android.permission.RECOVERY","RECOVERY"));
        lis.add(new AdhellPermissionInfo("android.permission.REGISTER_CALL_PROVIDER","REGISTER CALL PROVIDER"));
        lis.add(new AdhellPermissionInfo("android.permission.REGISTER_CONNECTION_MANAGER","REGISTER CONNECTION MANAGER"));
        lis.add(new AdhellPermissionInfo("android.permission.REGISTER_SIM_SUBSCRIPTION","REGISTER SIM SUBSCRIPTION"));
        lis.add(new AdhellPermissionInfo("android.permission.REGISTER_WINDOW_MANAGER_LISTENERS","REGISTER WINDOW MANAGER LISTENERS"));
        lis.add(new AdhellPermissionInfo("android.permission.REMOTE_AUDIO_PLAYBACK","REMOTE AUDIO PLAYBACK"));
        lis.add(new AdhellPermissionInfo("android.permission.REMOVE_DRM_CERTIFICATES","REMOVE DRM CERTIFICATES"));
        lis.add(new AdhellPermissionInfo("android.permission.REMOVE_TASKS","REMOVE TASKS"));
        lis.add(new AdhellPermissionInfo("android.permission.REORDER_TASKS","REORDER TASKS"));
        lis.add(new AdhellPermissionInfo("android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS","REQUEST IGNORE BATTERY OPTIMIZATIONS"));
        lis.add(new AdhellPermissionInfo("android.permission.REQUEST_INSTALL_PACKAGES","REQUEST INSTALL PACKAGES"));
        lis.add(new AdhellPermissionInfo("android.permission.RESET_FINGERPRINT_LOCKOUT","RESET FINGERPRINT LOCKOUT"));
        lis.add(new AdhellPermissionInfo("android.permission.RESET_SHORTCUT_MANAGER_THROTTLING","RESET SHORTCUT MANAGER THROTTLING"));
        lis.add(new AdhellPermissionInfo("android.permission.RESTART_PACKAGES","RESTART PACKAGES"));
        lis.add(new AdhellPermissionInfo("android.permission.RETRIEVE_WINDOW_CONTENT","RETRIEVE WINDOW CONTENT"));
        lis.add(new AdhellPermissionInfo("android.permission.RETRIEVE_WINDOW_TOKEN","RETRIEVE WINDOW TOKEN"));
        lis.add(new AdhellPermissionInfo("android.permission.REVOKE_RUNTIME_PERMISSIONS","REVOKE RUNTIME PERMISSIONS"));
        lis.add(new AdhellPermissionInfo("android.permission.SCORE_NETWORKS","SCORE NETWORKS"));
        lis.add(new AdhellPermissionInfo("android.permission.SEND_CALL_LOG_CHANGE","SEND CALL LOG CHANGE"));
        lis.add(new AdhellPermissionInfo("android.permission.SEND_DOWNLOAD_COMPLETED_INTENTS","SEND DOWNLOAD COMPLETED INTENTS"));
        lis.add(new AdhellPermissionInfo("android.permission.SEND_RESPOND_VIA_MESSAGE","SEND RESPOND VIA MESSAGE"));
        lis.add(new AdhellPermissionInfo("android.permission.SEND_SMS","SEND SMS"));
        lis.add(new AdhellPermissionInfo("android.permission.SEND_SMS_NO_CONFIRMATION","SEND SMS NO CONFIRMATION"));
        lis.add(new AdhellPermissionInfo("android.permission.SERIAL_PORT","SERIAL PORT"));
        lis.add(new AdhellPermissionInfo("android.permission.SET_ACTIVITY_WATCHER","SET ACTIVITY WATCHER"));
        lis.add(new AdhellPermissionInfo("android.permission.SET_ALWAYS_FINISH","SET ALWAYS FINISH"));
        lis.add(new AdhellPermissionInfo("android.permission.SET_ANIMATION_SCALE","SET ANIMATION SCALE"));
        lis.add(new AdhellPermissionInfo("android.permission.SET_DEBUG_APP","SET DEBUG APP"));
        lis.add(new AdhellPermissionInfo("android.permission.SET_INPUT_CALIBRATION","SET INPUT CALIBRATION"));
        lis.add(new AdhellPermissionInfo("android.permission.SET_KEYBOARD_LAYOUT","SET KEYBOARD LAYOUT"));
        lis.add(new AdhellPermissionInfo("android.permission.SET_ORIENTATION","SET ORIENTATION"));
        lis.add(new AdhellPermissionInfo("android.permission.SET_POINTER_SPEED","SET POINTER SPEED"));
        lis.add(new AdhellPermissionInfo("android.permission.SET_PREFERRED_APPLICATIONS","SET PREFERRED APPLICATIONS"));
        lis.add(new AdhellPermissionInfo("android.permission.SET_PROCESS_LIMIT","SET PROCESS LIMIT"));
        lis.add(new AdhellPermissionInfo("android.permission.SET_SCREEN_COMPATIBILITY","SET SCREEN COMPATIBILITY"));
        lis.add(new AdhellPermissionInfo("android.permission.SET_TIME","SET TIME"));
        lis.add(new AdhellPermissionInfo("android.permission.SET_TIME_ZONE","SET TIME ZONE"));
        lis.add(new AdhellPermissionInfo("android.permission.SET_WALLPAPER","SET WALLPAPER"));
        lis.add(new AdhellPermissionInfo("android.permission.SET_WALLPAPER_COMPONENT","SET WALLPAPER COMPONENT"));
        lis.add(new AdhellPermissionInfo("android.permission.SET_WALLPAPER_HINTS","SET WALLPAPER HINTS"));
        lis.add(new AdhellPermissionInfo("android.permission.SHUTDOWN","SHUTDOWN"));
        lis.add(new AdhellPermissionInfo("android.permission.SIGNAL_PERSISTENT_PROCESSES","SIGNAL PERSISTENT PROCESSES"));
        lis.add(new AdhellPermissionInfo("android.permission.START_ANY_ACTIVITY","START ANY ACTIVITY"));
        lis.add(new AdhellPermissionInfo("android.permission.START_PRINT_SERVICE_CONFIG_ACTIVITY","START PRINT SERVICE CONFIG ACTIVITY"));
        lis.add(new AdhellPermissionInfo("android.permission.START_TASKS_FROM_RECENTS","START TASKS FROM RECENTS"));
        lis.add(new AdhellPermissionInfo("android.permission.STATUS_BAR","STATUS BAR"));
        lis.add(new AdhellPermissionInfo("android.permission.STATUS_BAR_SERVICE","STATUS BAR SERVICE"));
        lis.add(new AdhellPermissionInfo("android.permission.STOP_APP_SWITCHES","STOP APP SWITCHES"));
        lis.add(new AdhellPermissionInfo("android.permission.STORAGE_INTERNAL","STORAGE INTERNAL"));
        lis.add(new AdhellPermissionInfo("android.permission.SUBSCRIBED_FEEDS_READ","SUBSCRIBED FEEDS READ"));
        lis.add(new AdhellPermissionInfo("android.permission.SUBSCRIBED_FEEDS_WRITE","SUBSCRIBED FEEDS WRITE"));
        lis.add(new AdhellPermissionInfo("android.permission.SUBSTITUTE_NOTIFICATION_APP_NAME","SUBSTITUTE NOTIFICATION APP NAME"));
        lis.add(new AdhellPermissionInfo("android.permission.SYSTEM_ALERT_WINDOW","SYSTEM ALERT WINDOW"));
        lis.add(new AdhellPermissionInfo("android.permission.TABLET_MODE","TABLET MODE"));
        lis.add(new AdhellPermissionInfo("android.permission.TEMPORARY_ENABLE_ACCESSIBILITY","TEMPORARY ENABLE ACCESSIBILITY"));
        lis.add(new AdhellPermissionInfo("android.permission.TETHER_PRIVILEGED","TETHER PRIVILEGED"));
        lis.add(new AdhellPermissionInfo("android.permission.TRANSMIT_IR","TRANSMIT IR"));
        lis.add(new AdhellPermissionInfo("android.permission.TRUST_LISTENER","TRUST LISTENER"));
        lis.add(new AdhellPermissionInfo("android.permission.TV_INPUT_HARDWARE","TV INPUT HARDWARE"));
        lis.add(new AdhellPermissionInfo("android.permission.TV_VIRTUAL_REMOTE_CONTROLLER","TV VIRTUAL REMOTE CONTROLLER"));
        lis.add(new AdhellPermissionInfo("android.permission.UPDATE_APP_OPS_STATS","UPDATE APP OPS STATS"));
        lis.add(new AdhellPermissionInfo("android.permission.UPDATE_CONFIG","UPDATE CONFIG"));
        lis.add(new AdhellPermissionInfo("android.permission.UPDATE_DEVICE_STATS","UPDATE DEVICE STATS"));
        lis.add(new AdhellPermissionInfo("android.permission.UPDATE_LOCK","UPDATE LOCK"));
        lis.add(new AdhellPermissionInfo("android.permission.UPDATE_LOCK_TASK_PACKAGES","UPDATE LOCK TASK PACKAGES"));
        lis.add(new AdhellPermissionInfo("android.permission.USER_ACTIVITY","USER ACTIVITY"));
        lis.add(new AdhellPermissionInfo("android.permission.USE_CREDENTIALS","USE CREDENTIALS"));
        lis.add(new AdhellPermissionInfo("android.permission.USE_FINGERPRINT","USE FINGERPRINT"));
        lis.add(new AdhellPermissionInfo("android.permission.USE_SIP","USE SIP"));
        lis.add(new AdhellPermissionInfo("android.permission.VIBRATE","VIBRATE"));
        lis.add(new AdhellPermissionInfo("android.permission.WAKE_LOCK","WAKE LOCK"));
        lis.add(new AdhellPermissionInfo("android.permission.WRITE_APN_SETTINGS","WRITE APN SETTINGS"));
        lis.add(new AdhellPermissionInfo("android.permission.WRITE_BLOCKED_NUMBERS","WRITE BLOCKED NUMBERS"));
        lis.add(new AdhellPermissionInfo("android.permission.WRITE_CALENDAR","WRITE CALENDAR"));
        lis.add(new AdhellPermissionInfo("android.permission.WRITE_CALL_LOG","WRITE CALL LOG"));
        lis.add(new AdhellPermissionInfo("android.permission.WRITE_CONTACTS","WRITE CONTACTS"));
        lis.add(new AdhellPermissionInfo("android.permission.WRITE_DREAM_STATE","WRITE DREAM STATE"));
        lis.add(new AdhellPermissionInfo("android.permission.WRITE_EXTERNAL_STORAGE","WRITE EXTERNAL STORAGE"));
        lis.add(new AdhellPermissionInfo("android.permission.WRITE_GSERVICES","WRITE GSERVICES"));
        lis.add(new AdhellPermissionInfo("android.permission.WRITE_MEDIA_STORAGE","WRITE MEDIA STORAGE"));
        lis.add(new AdhellPermissionInfo("android.permission.WRITE_PROFILE","WRITE PROFILE"));
        lis.add(new AdhellPermissionInfo("android.permission.WRITE_SECURE_SETTINGS","WRITE SECURE SETTINGS"));
        lis.add(new AdhellPermissionInfo("android.permission.WRITE_SETTINGS","WRITE SETTINGS"));
        lis.add(new AdhellPermissionInfo("android.permission.WRITE_SMS","WRITE SMS"));
        lis.add(new AdhellPermissionInfo("android.permission.WRITE_SOCIAL_STREAM","WRITE SOCIAL STREAM"));
        lis.add(new AdhellPermissionInfo("android.permission.WRITE_SYNC_SETTINGS","WRITE SYNC SETTINGS"));
        lis.add(new AdhellPermissionInfo("android.permission.WRITE_USER_DICTIONARY","WRITE USER DICTIONARY"));
        lis.add(new AdhellPermissionInfo("com.android.alarm.permission.SET_ALARM","SET ALARM"));
        lis.add(new AdhellPermissionInfo("com.android.launcher.permission.INSTALL_SHORTCUT","INSTALL SHORTCUT"));

        return lis;
    }
}
